### ISSUE TITLE
Translate Key Concepts » Identity into simplified Chinese

### ISSUE THREAD

**Issue by Zinnian** [hyperledger-labs/fabric-docs-cn#21]
Documents to be translated:

- [identity](https://github.com/hyperledger-labs/fabric-docs-cn/blob/1.2.0_zh-CN/docs/source/identity)

**Comment by xue35** [comment]
Am translating identity mixer (and generator), will cross check later.

**Comment by Zinnian** [comment]
> Am translating identity mixer (and generator), will cross check later.
I am translating network now, so identity can be assigned to you, if it is ok :)

**Comment by xue35** [comment]
Sure, pleasure.
