### ISSUE TITLE
Translate Key Concepts » Ledger, Use Case into simplified Chinese

### ISSUE THREAD

**Issue by Zinnian** [hyperledger-labs/fabric-docs-cn#25]
Documents to be translated:

- [ledger](https://github.com/hyperledger-labs/fabric-docs-cn/blob/1.2.0_zh-CN/docs/source/ledger)

- [usecases.rst](https://github.com/hyperledger-labs/fabric-docs-cn/blob/1.2.0_zh-CN/docs/source/usecases.rst)

**Comment by lijiachuan1982** [comment]
Please assign this to me, @JulienGuo , thanks.
