### ISSUE TITLE
Commands Reference » peer chaincode

### ISSUE THREAD

**Issue by stone-ch** [hyperledger-labs/fabric-docs-cn#357]

**Comment by Shitaibin** [comment]
Assign to me

**Comment by Fengcheng960512** [comment]
assign me

**Comment by stone-ch** [comment]
> assign me

这个 issue   @Fengcheng960512  已经有人认领了，你可以认领其他 issue，以防重复翻译。

**Comment by stone-ch** [comment]
@Shitaibin  翻译的怎么样了？超过两周未提交翻译 issue 可以被重新认领。

**Comment by Shitaibin** [comment]
> @Shitaibin 翻译的怎么样了？超过两周未提交翻译 issue 可以被重新认领。

@Fengcheng960512 @stone-ch 再分配吧，我现在 在翻译背书策略，这个忘记了

**Comment by stone-ch** [comment]
Done
