### ISSUE TITLE
Operations Guides » Raft Configuration

### ISSUE THREAD

**Issue by Shitaibin** [hyperledger-labs/fabric-docs-cn#366]

**Comment by Shitaibin** [comment]
Assign to me

**Comment by plutonji** [comment]
@Shitaibin 
之前的翻译，其中 WAL（包括 Ahead Log）翻译为日志头，个人认为不太准确。
要翻译的话按照约定应为“预写式日志”，或者干脆不翻译；您翻译的时候参考一下

**Comment by stone-ch** [comment]
> @Shitaibin
> 之前的翻译，其中 WAL（包括 Ahead Log）翻译为日志头，个人认为不太准确。
> 要翻译的话按照约定应为“预写式日志”，或者干脆不翻译；您翻译的时候参考一下

赞同

**Comment by Shitaibin** [comment]
@plutonji 好的

**Comment by Shitaibin** [comment]
@plutonji 这一篇，之前Github上翻译一半了，是不是你翻译的？要不要继续你翻译，我选其他

**Comment by plutonji** [comment]
不是我翻译的，不过我本地确实已经翻译好了 ;-)

**Comment by stone-ch** [comment]
@Shitaibin  翻译的怎么样了？如果差得多的话 @plutonji  可以把翻译的内容提交了，@Shitaibin   来review。

**Comment by stone-ch** [comment]
Done
