### ISSUE TITLE
Operations Guides » Migrating from Kafka to Raft

### ISSUE THREAD

**Issue by stone-ch** [hyperledger-labs/fabric-docs-cn#412]

**Comment by stone-ch** [comment]
@suchongming  你翻译的怎么样了?  @Fengcheng960512 没有认领这篇文档，但是提交了一版翻译。你可以再次提交你的翻译，或者 review 已提交的翻译。

**Comment by stone-ch** [comment]
@Fengcheng960512 以后可以注意一下，其他人认领的任务就不要翻译了，避免重复工作量。

**Comment by Fengcheng960512** [comment]
好的知道了，抱歉

**Comment by suchongming** [comment]
@stone-ch 翻译一半多了，预计周五周六完结

**Comment by suchongming** [comment]
@stone-ch  那我去领取他任务吗？

**Comment by stone-ch** [comment]
@suchongming  目前fabric 1.4.2 的文档基本翻译完了，在准备将所有文档review一遍，暂时没有新的issue，你根据你的翻译review一下 @Fengcheng960512 翻译完成的内容吧，包括格式和内容。

**Comment by suchongming** [comment]
@stone-ch 好的

**Comment by stone-ch** [comment]
Done
