### ISSUE TITLE
release-2.0: Operations Guides » Using a Hardware Security Module (HSM)

### ISSUE THREAD

**Issue by stone-ch** [hyperledger-labs/fabric-docs-cn#480]
assign me

**Comment by bessieIsBinBIn** [comment]
assign me

**Comment by stone-ch** [comment]
> assign me

该issue已分配给其他人，请查看该链接 https://hyperledger-fabric-cn.readthedocs.io/zh/release-2.0/，查找尚未翻译的内容，创建新的issue，例如 https://hyperledger-fabric-cn.readthedocs.io/zh/release-2.0/write_first_app.html 这篇文章，创建标题为“release-2.0: Tutorials » Writing Your First Application” 的issue，并在下边添加评论，管理员便会把这个issue分配给你。

**Comment by stone-ch** [comment]
@bessieIsBinBIn  已经新增了其他issue，你可以在issue下边添加评论，认领了。

**Comment by stone-ch** [comment]
assign me to review
