### ISSUE TITLE
release-2.0: Commands Reference » peer

### ISSUE THREAD

**Issue by stone-ch** [hyperledger-labs/fabric-docs-cn#508]

**Comment by Vegard-Bear** [comment]
assign me to review

**Comment by Vegard-Bear** [comment]
你好，我已经提交PR了，但是忘记关联到这个issue了，咋整啊😂
[PR 信息](https://github.com/hyperledger-labs/fabric-docs-cn/pull/615/commits/9e1e9457200c363206381290d271701296dc9744)

**Comment by stone-ch** [comment]
完成校对
