### ISSUE TITLE
release-2.0: Tutorials » Using Private Data in Fabric

### ISSUE THREAD

**Issue by stone-ch** [hyperledger-labs/fabric-docs-cn#537]

**Comment by zcqzcg** [comment]
Asign me pls

**Comment by zcqzcg** [comment]
我在 release-2.0  分支怎么找不到这篇文章： Docs » Tutorials » Using Private Data in Fabric

**Comment by stone-ch** [comment]
assign to review

**Comment by stone-ch** [comment]
@zcqzcg  翻译时应尽量尊重原文意思，不要完全按照自己的语言翻译。需要在原文中增加翻译者的理解的话，最好增加“译者注”标识，不能随便增删内容。

**Comment by stone-ch** [comment]
已校对译文
