### ISSUE TITLE
各位，为什么FabricCA的文档很久没有继续翻译了？请问有翻译计划吗？

### ISSUE THREAD

**Issue by mrchar** [hyperledger-labs/fabric-docs-cn#618]
我现在在学习如何FabricCA，最然有英文的文档可以看，但是阅读中文的文档还是更方便一些，我看到FabricCA的文档最近的提交已经过去很久了，难道没有翻译计划了吗？请问我可以帮上忙吗？

**Comment by stone-ch** [comment]
因为 CA 文档中没有太复杂的东西都是讲如何使用，前段时间又在赶 Fabric 1.4 和 2.0 的文档，所以就没有翻译。你有兴趣翻译么？我这两天把 CA 的文档加进来。

**Comment by mrchar** [comment]
我最近正在参照CA的文件进行部署，但是感觉CA的文档讲的有点乱，我不确定我短期内有精力翻译CA文档，但是我会根据自己的工作进度选择性的翻译部分内容。

**Comment by stone-ch** [comment]
Fabric-CA 英文文档已添加到 fabric-ca-release1.4 分支，fabric和fabric-ca是两个不同的项目，文档也在不同的readthedocs项目中，翻译完成后会和fabric-ca维护者协商集成到官方readthedocs中。
