### ISSUE TITLE
Translate Update for V1.3: Tutorials - Chaincode for developers

### ISSUE THREAD

**Issue by lijiachuan1982** [hyperledger-labs/fabric-docs-cn#72]
There are lots of differences between [V1.3 Version](https://hyperledger-fabric.readthedocs.io/en/release-1.3/chaincode4ade.html) and [V1.2 translated version](https://hyperledger-fabric-cn.readthedocs.io/zh/1.2.0_zh-cn/chaincode4ade.html), need to update

**Comment by alexanderhawl** [comment]
there is a wrong translation in this chapter. the part title  is Terminal 2- Build&Start the chaincode. In the orignal sentence is : 
Now run the chaincode:
CORE_PEER_ADDRESS=peer:7052 CORE_CHAINCODE_ID_NAME=mycc:0 ./sacc
but the Chinese translation is 
CORE_PEER_ADDRESS=peer:7051 CORE_CHAINCODE_ID_NAME=mycc:0 ./sacc
And after I did the experiment, I found the translation is wrong.

**Comment by lijiachuan1982** [comment]
hi @alexanderhawl , the port number in V1.2 and V1.3 are both 7052, whether you are referring the 1.2 or 1.3 version of documents? Thanks.

**Comment by alexanderhawl** [comment]
I donot know which version the document is. The site is https://hyperledgercn.github.io/hyperledgerDocs/chaincode_developers_zh/#2.  And  my fabric version is 1.3. Maybe I didnot find the right translation version.

________________________________

**Comment by lijiachuan1982** [comment]
@alexanderhawl , please check this one, and this is not translated yet for 1.3 version.

https://hyperledger-fabric-cn.readthedocs.io/zh/latest/chaincode4ade.html

**Comment by alexanderhawl** [comment]
The 1.3 verison is right.
________________________________
